### ISSUE TITLE
Qpkg for TS-431P

### ISSUE THREAD

**Issue by andyyap** [dynek/crashplan-qpkg#33]
Hi I would like to find out if there is a way to create qpkg for TS-431P? I have tried most of the one within the app-store. All come back with incompitable architecture.

**Comment by dynek** [comment]
Hello,

Problem with this model is that it runs an ARM processor and CrashPlan / Code42 made it impossible for anyone to run their service on other architecture than x86. This is due to a closed-source/home-made library specifically built for x86 cpus.

At the moment whatever you would be able to install will fail starting.

Sorry for that.
